# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0002_auto_20171110_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbuser',
            name='followers',
            field=models.ManyToManyField(to='weibo.WBUser', verbose_name='粉丝'),
        ),
        migrations.AlterField(
            model_name='wbuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='昵称'),
        ),
    ]
